CREATE DATABASE Shop

USE Shop

CREATE TABLE Category
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
IsDeleted BIT NOT NULL,
CreatedAt Date NOT NULL,
UpdatedAt Date NOT NULL
)

CREATE TABLE Product
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL,
Price FLOAT NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Category(Id),
IsDeleted BIT NOT NULL,
CreatedAt Date NOT NULL,
UpdatedAt Date NOT NULL
)